# Site settings
title:          Dugi
description:    "요기수구더기의 블로그"
baseurl:        ""
url:            "https://dugidugi.github.io"

# Google Analytics
google_analytics: UA-59679608-1

# Author
author:
  name:         Yooduck Hwang
  url:          https://dugidugi.github.io
  email:        xxxxx@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         